version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: todo_list_app
    command: >
      /bin/bash -c "alembic upgrade head && cd src && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    volumes:
      - .:/fastapi_app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgdbdata: null
