"""Changed Tokentable model

Revision ID: d1d4c4546ac9
Revises: b53e235dd88f
Create Date: 2023-10-16 21:57:27.629779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4c4546ac9'
down_revision: Union[str, None] = 'b53e235dd88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'user_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
